// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeo_raccsxrfICh0tvLDSXzyf4ANXu6zs',
    appId: '1:501898802793:web:80cfa2c7f4b646479cd4f8',
    messagingSenderId: '501898802793',
    projectId: 'chat-material3-93569',
    authDomain: 'chat-material3-93569.firebaseapp.com',
    storageBucket: 'chat-material3-93569.appspot.com',
    measurementId: 'G-D8F51D01DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBng1yUt17CNlUeNMb8yUUDtHfsYE6OI',
    appId: '1:501898802793:android:1d37a523fe8b21ee9cd4f8',
    messagingSenderId: '501898802793',
    projectId: 'chat-material3-93569',
    storageBucket: 'chat-material3-93569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrUsmGtzo7ZY9UPIySxSq5T0G8lFQU5Kc',
    appId: '1:501898802793:ios:d69dda7aa7db58919cd4f8',
    messagingSenderId: '501898802793',
    projectId: 'chat-material3-93569',
    storageBucket: 'chat-material3-93569.appspot.com',
    iosBundleId: 'com.example.chatMaterial3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrUsmGtzo7ZY9UPIySxSq5T0G8lFQU5Kc',
    appId: '1:501898802793:ios:d69dda7aa7db58919cd4f8',
    messagingSenderId: '501898802793',
    projectId: 'chat-material3-93569',
    storageBucket: 'chat-material3-93569.appspot.com',
    iosBundleId: 'com.example.chatMaterial3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeo_raccsxrfICh0tvLDSXzyf4ANXu6zs',
    appId: '1:501898802793:web:61b7bc350a8c248d9cd4f8',
    messagingSenderId: '501898802793',
    projectId: 'chat-material3-93569',
    authDomain: 'chat-material3-93569.firebaseapp.com',
    storageBucket: 'chat-material3-93569.appspot.com',
    measurementId: 'G-KG6ZDCG1S2',
  );
}
